[rsspls]
output = "/tmp"

[[feed]]
title = "vitapedia.pl"
filename = "vitapedia.rss"

[feed.config]
url = "https://vitapedia.pl"
item = "li.list-results__item"
heading = "h3"
link = "a"
summary ="a div ul li:nth-child(2)"
# albo opis
# summary = "a div p"
